try
	colorscheme molokai
catch /E185.*/
	colorscheme evening
endtry
highlight DiffAdd    guifg=black guibg=lightblue
highlight DiffChange guifg=black guibg=lightyellow
highlight DiffDelete guifg=black guibg=lightred
highlight DiffText   guifg=black guibg=violet
" function! GuiTabLabel()
" 	let label = ''
" 	let bufnrlist = tabpagebuflist(v:lnum)
" 	for bufnr in bufnrlist
" 		if getbufvar(bufnr, "&modified")
" 			let label = '[+]'
" 			break
" 		endif
" 	endfor
" 	if label != '' | let label .= ' ' | endif
" 	return label . bufname(bufnrlist[tabpagewinnr(v:lnum) - 1])
" endfunction
" set guitablabel=%{GuiTabLabel()}
set guitablabel=[%N-%n]\ %-20.20F
set guioptions+=aci
if has('win32')
	set guioptions-=mrLT
	set guifont=Ricty:h14,MS_Gothic:h14
	set renderoptions=type:directx,renmode:5
else
	set guioptions-=mrLtT
	set guifont=Ricty\ 14
endif
set columns=120
set lines=40
runtime gvimrc.local.vim
