colorscheme evening
highlight DiffAdd    guifg=black guibg=lightblue
highlight DiffChange guifg=black guibg=lightyellow
highlight DiffDelete guifg=black guibg=lightred
highlight DiffText   guifg=black guibg=violet
if has('win32')
	set guifont=Ricty:h12,MS_Gothic:h12
	set rop=type:directx,renmode:5
else
	set guifont=Ricty\ 12
endif
set columns=120
set lines=40
