source ~/.exrc
syntax on
set title
set ruler
set nowrap
set cursorline
set whichwrap=h,l
set noundofile
if has('mouse')
	set mouse=a
	set nomousehide
endif
set guioptions=aeimgt
set showtabline=2
set showcmd
set laststatus=2
set history=1000
set wildmenu
set wildmode=list:longest
set modeline
set modelines=5
set backspace=indent,eol,start
set hidden
set ignorecase
set smartcase
set incsearch
set hlsearch
set smarttab
set cindent
map  :nohl
set clipboard=unnamed,unnamedplus,autoselect
set browsedir=buffer
set list
set listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%,eol:↲
filetype on
filetype plugin on
filetype indent on
